DROP TABLE IF EXISTS endpoint_hit CASCADE;

CREATE TABLE IF NOT EXISTS endpoint_hit
(
    endpoint_hit_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    app             VARCHAR(30)                             NOT NULL,
    uri             VARCHAR(2000)                           NOT NULL,
    ip              VARCHAR(15)                             NOT NULL,
    timestamp       TIMESTAMP WITHOUT TIME ZONE             NOT NULL
);